use_frameworks!

target 'Portfolio'
  pod 'BrightFutures', '4.0.0-beta.1'
  pod 'SwiftHTTP', '1.0.5'
  pod 'SnapKit', '0.20.0'
  pod 'Charts', '2.2.4'
  pod 'Unbox', '1.4'
  pod 'MaterialKit', '0.4'
  pod 'Google-Material-Design-Icons-Swift', '1.0.1'
  pod 'Font-Awesome-Swift', '1.4.7'
  pod 'CSwiftV', '0.0.3'

target 'PortfolioTests'
  pod 'BrightFutures', '4.0.0-beta.1'
  pod 'SwiftHTTP', '1.0.5'
  pod 'SnapKit', '0.20.0'
  pod 'Charts', '2.2.4'
  pod 'Unbox', '1.4'
  pod 'MaterialKit', '0.4'
  pod 'Google-Material-Design-Icons-Swift', '1.0.1'
  pod 'Font-Awesome-Swift', '1.4.7'
  pod 'CSwiftV', '0.0.3'